services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./id_map.json:/app/id_map.json
      - ./settings.json:/app/settings.json
      - ./subjects.json:/app/subjects.json
